config/routes.rb
NuFolka::Application.routes.draw do
  resources :products
  
  match 'products/test',   to: 'products#show'
  

end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :title, :price, :description, :image_url, :buy_button
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  
  respond_to :html, :js
  
  def index
    @products = Product.all
    
    respond_to do |format|
         format.html
         format.js
       end
  end

  def show
    @product = Product.find(params[:id])
     respond_to do |format|
           format.html
           format.js
     end
  end

  def new
    @product = Product.new
    respond_to do |format|
         format.html
         format.js
       end
  end

  def create
    @product = Product.new(params[:product])
    if @product.save
      redirect_to @product, :notice => "Successfully created product."
    else
      render :action => 'new'
    end
    respond_to do |format|
      format.html { redirect_to @product}
      format.js
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update_attributes(params[:product])
      redirect_to @product, :notice  => "Successfully updated product."
    else
      render :action => 'edit'
    end
  end
  
  
  def test
    @product = Product.find(params[:id])
  end  
  
  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_url, :notice => "Successfully destroyed product."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  def print_price(price)
      number_to_currency price
    end
    
  def print_description(description)
    a = String
    a = description.split('.')
    a.each do |z|
      puts a[1...a.length]
    end
  end
end

app/views/layouts/_footer.html.erb
<footer>
	<div class="footer">
		 <p style="text-align:center"><pre style="color:red">Designed by <a  href="http://twitter.com/#!/JulioAhuactzin">@JulioAhuactzin</a>. Powered by <a href="http://twitter.com/#!/monkeymachin">@monkeymachin</a> </pre></p>
  	</div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
    <div class="container">
      <%= link_to "NuFolka Complementos", products_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
		  <li><%= link_to "Bio", "#"%></li>
          <li><%= link_to "Inicio", products_path%></li>
        </ul>
      </nav>
    </div>
  </div>


</header>

          

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
	  <title>NuFolka Complementos | Diseño Textil Mexicano <%= controller.action_name %></title>  
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "jquery", "application" %>

    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
	<body data-spy="scroll" data-target=".bs-docs-sidebar" data-twttr-rendered="true">
	
<p style="color: green"><%= flash[:notice] %></p>

<div class="wrapper">
	<%= render 'layouts/header' %>
      <div class="sidebar">
    </div>
	<div style="background-image:url('/background.gif');background-repeat:repeat;"class="well">

	  
	    <div class="row">
	      <%= yield(:test)%>
	      <div class="span12">
      		<%= yield %>

			<div class="modal-body" id="modal-window">
			</div>

    	</div>
	</div>
</div>
	<%= render 'layouts/footer' %>
</div>
</body>
</html>

app/views/products/_form.html.erb
<div id="new_review">
<%= form_for @product do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.label :image_url %><br />
    <%= f.text_field :image_url %>
  </p>
  <p>
    <%= f.label :buy_button %><br />
    <%= f.text_area :buy_button %>
  </p>
  <p><%= f.submit %></p>
<% end %>
</div>

app/views/products/_show.html.erb
<!--<div class="modal hide fade" id="modal-window">
  <div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
  </div>

  <div class="modal-body center">
	  
    </div>
  	<div class="modal-footer">
	    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
	    <button class="btn btn-primary">Save changes</button>
  	</div>
</div>
</div> -->

app/views/products/_test.html.erb
<div class="modal" id="modal-window">
  <div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
	<h2><%= @product.title %></h2>
  </div>
  <div class="modal-body center">
	<div class="row">
     	<div class="span4">	
			<p><%= link_to image_tag("/nufolka/#{@product.image_url}", :border => 0, :alt => '', :title => ''), product_path, :class => 'dock-item'%></p>
			
		</div>
		<div class="span4">
			<div class="caption">
				<p>Descripción: <span><%= print_description(@product.description) %></span></p>
				<p>Precio: <span><strong><%= print_price(@product.price) %></strong></span></p>
				<p><%= link_to "View", product_path(@product) %></p>
	  		
  			</div>
		</div>
	</div>
  	<div class="modal-footer">&nbsp;</div>
  </div>
</div>

app/views/products/bio.html.erb
<div class="span6 offset1">
		        <section id="file-structure">
					<h1>El "background" de NuFolka Complementos...</h1>
					<p class="lead">Siempre he tratado de ser yo misma de hacer y amar lo que hago y lo que doy, eso me ha llevado a no frenar mi creatividad y en gran medida a ser original y autentica.
Estudie diseño textil por la versatilidad que tienen estos materiales y por la cultura, historia y significado que hay detrás de estos. 
En algún momento de mi vida sentí el impulso de dejar huella y decidí formar NuFolka (que significa dentro de mi entendimiento y con intención de que lo sea para los demás) Nuevo Folklor un juego de palabras y pronunciaciones. Son complementos (accesorios) diseñados y hechos siempre con significado, con una intención y utilidad para mi y para quien los use.
Creo que ya todo esta inventado, está sobre la mesa simplemente para que uno tome y entonces transformas y vuelves a crear algo "nuevo" que en realidad es eso que estaba pero con una nueva perspectiva y con elementos que lo enriquecen o lo adaptan a un estilo.
Me encanta transformar, crear, diseñar y también disfruto y me alimento de ver que esto que amo transciende.<br/><br/>

Saludos! <a href="">KaiRamirez</a></p>
			</section>
				</div>
				<div class="span4">
					<img style="margin-top:20%" src="assets/img/nufolka/bio.jpg"/>
				</div>

app/views/products/edit.html.erb
<% title "Edit Product" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @product %> |
  <%= link_to "View All", products_path %>
</p>


<% content_for :head do %>
	
	<% end %>

app/views/products/index.html.erb
<div class="hero-unit">
  <h1>Nufolka Complementos</h1>
  <h2>Complementos para tu estilo</h2>
</div>

<% content_for :test do %>
	
	<div class="span3 bs-docs-sidebar">
    	<ul class="nav nav-list bs-docs-sidenav affix">
		          <li class=""><a href="#download-bootstrap"><i class="icon-chevron-right"></i> Download</a></li>
		          <li class=""><a href="#file-structure"><i class="icon-chevron-right"></i> File structure</a></li>
		          <li class=""><a href="#contents"><i class="icon-chevron-right"></i> What's included</a></li>
		          <li><a href="#examples"><i class="icon-chevron-right"></i> Examples</a></li>
		          <li><a href="#what-next"><i class="icon-chevron-right"></i> What next?</a></li>
		        </ul>
  </div>



<% end %>

<% title "Products" %>
<div class="container">
	
	<div class="clearfix masonry" id="contenedor">
		  
		<% @products.each do |product| %>
				<div class="span4">	
						<div class="box photo col3 masonry-brick">
	            			<h2><%= product.title %></h2>
							<p><%= image_tag "/nufolka/#{product.image_url}" %></p>
							<div class="caption">
								<p>Descripción: <span><%= print_description(product.description) %></span></p>
								<p>Precio: <span><strong><%= print_price(product.price) %></strong></span></p>
								<p><%= link_to "View", product_path(product) %></p>
								
								<p><%= link_to "Edit", product_path(product), {:remote => true, 'data-controls-modal' =>  "modal-window", 'data-backdrop' => true, 'data-keyboard' => true} %></p>
								
								
						    </div>
			            </div>
		         </div>
		 <% end %>
	</div>
</div>



	
<script> 
 
  $(function(){

    var $container = $('#contenedor');
  
    $container.imagesLoaded( function(){
      $container.masonry({
        itemSelector : '.box'
      });
    });
  
  });
  </script>

			

app/views/products/new.html.erb
<% title "New Product" %>

<%= render 'form' %>

<p><%= link_to "Back to List", products_path %></p>

app/views/products/show.html.erb
<% title "Product" %>


<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>
<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>
<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>
<p>
  <strong>Image Url:</strong>
  <%= @product.image_url %>
</p>
<p>
  <strong>Buy Button:</strong>
  <%= @product.buy_button %>
</p>

<p>
  <%= link_to "Edit", edit_product_path(@product) %> |
  <%= link_to "Destroy", @product, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", products_path %>
</p>


	 

app/views/products/show.js.erb
/*
$('#modal-window').modal('toggle');
/*$(".modal-body").before("<%= escape_javascript(render 'test', :formats => [:html]) %>");*/

/*$('.modal-body').html("<%= escape_javascript(render('test')) %>");

console.log("test")*/
$('#modal-window').modal('show');
$('.modal-body').html("<%= escape_javascript(render :partial => 'test', :object => @products) %>");